name: Generate Diagram

on:
  push:
    branches:
      - main  # or specify any branch you want

jobs:
  generate-diagram:
    runs-on: ubuntu-latest  # You can use other OS types, e.g., macos-latest or windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # or specify your version of Python

    - name: Install dependencies
      run: |
        pip install diagrams

    - name: Run diagram script
      run: |
        python diagram_script.py  # Make sure your script generates the diagram file here
    
    - name: Commit and push diagram
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add web_service_diagram.png  # Adjust the filename if needed
        git commit -m "Automated diagram generation"
        git push

